# Generated by Django 5.2.8 on 2025-11-16 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('role', models.CharField(choices=[('petani', 'Petani'), ('mahasiswa', 'Mahasiswa'), ('peneliti', 'Peneliti'), ('siswa', 'Siswa'), ('lainnya', 'Lainnya')], default='petani', max_length=20, verbose_name='Peran')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Login terakhir')),
            ],
            options={
                'verbose_name': 'Pengguna Forum',
                'verbose_name_plural': 'Pengguna Forum',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('content', models.TextField(verbose_name='Isi Postingan')),
                ('category', models.CharField(choices=[('penyakit', 'Penyakit Stroberi'), ('perawatan', 'Tips Perawatan'), ('pengalaman', 'Pengalaman Lapangan'), ('teknis', 'Pertanyaan Teknis'), ('umum', 'Diskusi Umum')], default='umum', max_length=20, verbose_name='Kategori')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('views', models.IntegerField(default=0, verbose_name='Jumlah Dilihat')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.forumuser', verbose_name='Penulis')),
            ],
            options={
                'verbose_name': 'Postingan Forum',
                'verbose_name_plural': 'Postingan Forum',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Isi Komentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.forumpost', verbose_name='Postingan')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.forumuser', verbose_name='Penulis')),
            ],
            options={
                'verbose_name': 'Komentar Forum',
                'verbose_name_plural': 'Komentar Forum',
                'ordering': ['created_at'],
            },
        ),
    ]
