# Generated by Django 5.2.8 on 2025-11-16 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20, unique=True, verbose_name='ID Member')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Login terakhir')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sensor_update', 'Update Sensor'), ('detection_new', 'Deteksi Baru'), ('sensor_warning', 'Peringatan Sensor'), ('device_offline', 'Perangkat Offline'), ('device_added', 'Perangkat Ditambahkan')], max_length=20, verbose_name='Tipe Notifikasi')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('is_read', models.BooleanField(default=False, verbose_name='Sudah Dibaca')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main.member', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RangBotDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Seri')),
                ('device_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Perangkat')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Tidak Aktif'), ('offline', 'Offline')], default='offline', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('last_data_update', models.DateTimeField(blank=True, null=True, verbose_name='Update Data Terakhir')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ditambahkan pada')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangbot_devices', to='main.member', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Perangkat RangBot',
                'verbose_name_plural': 'Perangkat RangBot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='URL Gambar')),
                ('disease_detected', models.CharField(blank=True, max_length=200, null=True, verbose_name='Penyakit Terdeteksi')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='Tingkat Keyakinan')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lokasi')),
                ('detection_type', models.CharField(choices=[('auto', 'Otomatis'), ('manual', 'Manual')], default='auto', max_length=20, verbose_name='Tipe Deteksi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Deteksi')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='main.rangbotdevice', verbose_name='Perangkat')),
            ],
            options={
                'verbose_name': 'Riwayat Deteksi',
                'verbose_name_plural': 'Riwayat Deteksi',
                'ordering': ['-created_at'],
            },
        ),
    ]
