# Generated by Django 5.2.8 on 2025-11-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_member_notification_rangbotdevice_detectionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangbotdevice',
            name='covered_blocks',
            field=models.CharField(blank=True, help_text='Contoh: A, B atau C, D', max_length=200, null=True, verbose_name='Blok yang Dicakup'),
        ),
        migrations.AlterField(
            model_name='rangbotdevice',
            name='device_name',
            field=models.CharField(blank=True, help_text='Contoh: RangBot 1, RangBot 2', max_length=100, null=True, verbose_name='Nama Perangkat'),
        ),
    ]
