# Generated by Django 4.2.7 on 2025-11-16 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rangbotdevice_covered_blocks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Login terakhir')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='is_registered',
            field=models.BooleanField(default=False, help_text='True jika sudah melakukan registrasi dengan Member ID', verbose_name='Sudah Registrasi'),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Username'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nama Customer')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email Customer')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Nomor Telepon')),
                ('customer_address', models.TextField(verbose_name='Alamat Instalasi')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Greenhouse/Perusahaan')),
                ('qty_basic', models.IntegerField(default=0, verbose_name='Jumlah Paket Basic')),
                ('qty_professional', models.IntegerField(default=0, verbose_name='Jumlah Paket Professional')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Harga')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('verified', 'Terverifikasi'), ('rejected', 'Ditolak')], default='pending', max_length=20, verbose_name='Status')),
                ('member_id', models.CharField(blank=True, help_text='Diisi otomatis setelah verifikasi', max_length=20, null=True, unique=True, verbose_name='Member ID')),
                ('is_reorder', models.BooleanField(default=False, verbose_name='Pembelian Ulang')),
                ('original_member_id', models.CharField(blank=True, help_text='Untuk pembelian ulang', max_length=20, null=True, verbose_name='Member ID Asal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Diverifikasi pada')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_orders', to='main.admin', verbose_name='Diverifikasi oleh')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='main.purchaseorder', verbose_name='Purchase Order'),
        ),
        migrations.AddField(
            model_name='rangbotdevice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Order yang menghasilkan device ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='main.purchaseorder', verbose_name='Purchase Order'),
        ),
    ]
