# Generated by Django 4.2.7 on 2025-11-18 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_admin_member_is_registered_alter_member_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Login terakhir')),
            ],
            options={
                'verbose_name': 'Customer Service',
                'verbose_name_plural': 'Customer Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Pertanyaan')),
                ('answer', models.TextField(verbose_name='Jawaban')),
                ('order', models.IntegerField(default=0, help_text='Urutan tampil (0 = pertama)', verbose_name='Urutan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional')], max_length=20, unique=True, verbose_name='Tipe Paket')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Paket')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Harga')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('features', models.TextField(blank=True, help_text='Satu fitur per baris', null=True, verbose_name='Fitur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.admin', verbose_name='Diperbarui oleh')),
            ],
            options={
                'verbose_name': 'Informasi Produk',
                'verbose_name_plural': 'Informasi Produk',
                'ordering': ['package_type'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('content', models.TextField(verbose_name='Isi Artikel')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL Gambar')),
                ('is_published', models.BooleanField(default=False, verbose_name='Dipublikasikan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='main.admin', verbose_name='Dibuat oleh')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['-created_at'],
            },
        ),
    ]
