# Generated by Django 4.2.7 on 2025-11-18 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customerservice_faq_productinfo_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('order_verified', 'Verifikasi Pembelian'), ('order_rejected', 'Pembelian Ditolak'), ('member_created', 'Member ID Dibuat'), ('serial_created', 'Nomor Seri Dibuat'), ('member_updated', 'Data Member Diperbarui'), ('member_deactivated', 'Member Dinonaktifkan'), ('member_activated', 'Member Diaktifkan'), ('serial_updated', 'Nomor Seri Diperbarui'), ('product_updated', 'Produk Diperbarui'), ('admin_created', 'Admin Dibuat'), ('admin_deactivated', 'Admin Dinonaktifkan'), ('cs_created', 'Customer Service Dibuat'), ('cs_deleted', 'Customer Service Dihapus'), ('system_error', 'Error Sistem')], max_length=50, verbose_name='Tipe Aksi')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Data tambahan dalam format JSON', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='main.admin', verbose_name='Dilakukan oleh')),
                ('related_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='main.rangbotdevice', verbose_name='Device Terkait')),
                ('related_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='main.member', verbose_name='Member Terkait')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='main.purchaseorder', verbose_name='Purchase Order Terkait')),
            ],
            options={
                'verbose_name': 'Log Aktivitas',
                'verbose_name_plural': 'Log Aktivitas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='main_activi_created_8e9fba_idx'), models.Index(fields=['action_type'], name='main_activi_action__40258a_idx')],
            },
        ),
    ]
