# Generated by Django 4.2.7 on 2025-11-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('transfer', 'Transfer Bank'), ('credit', 'Kartu Kredit'), ('installment', 'Cicilan'), ('leasing', 'Leasing')], max_length=20, null=True, verbose_name='Metode Pembayaran'),
        ),
    ]
