# Generated by Django 4.2.7 on 2025-11-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_member_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subjek')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('status', models.CharField(choices=[('new', 'Baru'), ('read', 'Sudah Dibaca'), ('replied', 'Sudah Dibalas'), ('archived', 'Diarsipkan')], default='new', max_length=20, verbose_name='Status')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Dibalas')),
                ('reply_message', models.TextField(blank=True, null=True, verbose_name='Balasan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_messages', to='main.customerservice', verbose_name='Dibalas oleh')),
            ],
            options={
                'verbose_name': 'Pesan Customer Service',
                'verbose_name_plural': 'Pesan Customer Service',
                'ordering': ['-created_at'],
            },
        ),
    ]
