# Generated by Django 4.2.7 on 2025-11-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_forumuser_username_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='is_cs_reply',
            field=models.BooleanField(default=False, verbose_name='Jawaban dari CS'),
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='replied_by_cs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_replies', to='main.customerservice', verbose_name='Dijawab oleh CS'),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.forumuser', verbose_name='Penulis'),
        ),
    ]
