# Generated by Django 4.2.7 on 2025-11-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_add_forumcomment_cs_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumcomment',
            name='is_cs_reply',
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='is_cs_note',
            field=models.BooleanField(default=False, verbose_name='Catatan CS'),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='replied_by_cs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_notes', to='main.customerservice', verbose_name='Ditulis oleh CS'),
        ),
    ]
